//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperStore.Sales.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeveloperStore.Sales.Application.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be less than or equal to {1}..
        /// </summary>
        internal static string LessThanOrEqualValidatorDetail {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidatorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string LessThanOrEqualValidatorMessage {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanOrEqualValidator.
        /// </summary>
        internal static string LessThanOrEqualValidatorType {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sale cannot be processed because no items were provided in the request..
        /// </summary>
        internal static string NoItemsErrorDetail {
            get {
                return ResourceManager.GetString("NoItemsErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sale must have at least one item.
        /// </summary>
        internal static string NoItemsErrorMessage {
            get {
                return ResourceManager.GetString("NoItemsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoItemsError.
        /// </summary>
        internal static string NoItemsErrorType {
            get {
                return ResourceManager.GetString("NoItemsErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceNotFound.
        /// </summary>
        internal static string ResourceNotFoundType {
            get {
                return ResourceManager.GetString("ResourceNotFoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale with Id {0} was not found.
        /// </summary>
        internal static string SaleNotFoundDetail {
            get {
                return ResourceManager.GetString("SaleNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale not found.
        /// </summary>
        internal static string SaleNotFoundMessage {
            get {
                return ResourceManager.GetString("SaleNotFoundMessage", resourceCulture);
            }
        }
    }
}
